#relationtest:
#  股东: test
#relation:
#  - 股东:
#    - 前10大流通股东（公司和公司）
#    - 前10大流通股东（人和公司）
#    - 前10大股东（公司和公司）
#    - 前10大股东（人和公司）
#    - 工商股东信息
#    - 股东及出资信息（年报）
#    - 母公司（公司和公司）
#    - 母公司（人和公司）
#  实际控制人:
#  - 实际控制人（人和公司）
#  - 实际控制人（公司和公司）
#  股权:
#  - 子公司
#  - 合营联营企业
#  - 重大股权投资<-
#  - 对外投资（年报）<-
#  高管:
#  - 董监高
#  - 亲属
#  - 股东—高管持股（人和公司）<-
#  - 其他公司任职
#  - 股东单位任职
#  客户:
#  - 关联交易—销售（公司和公司）
#  - 关联交易—销售（人和公司）
#  - 关联交易—应收账款（公司和公司）
#  - 关联交易—应收账款（人和公司）
#  - 重要客户—主要客户（公司和公司）
#  - 重要客户—主要客户（人和公司）
#  - 重要客户—应收账款（公司和公司）
#  - 重要客户—应收账款（人和公司）
#  - 重要客户预收款（公司和公司）
#  - 重要客户预收款（人和公司）
#  - 重要其他应收款（公司和公司）
#  - 重要其他应收款（人和公司）
#  供应商:
#  - 关联交易—采购（公司和公司）
#  - 关联交易—采购（人和公司）
#  - 关联交易—应付账款（公司和公司）
#  - 关联交易—应付账款（人和公司）
#  - 供应商（公司和公司）
#  - 供应商（人和公司）
#  - 供应商应付款（公司和公司）
#  - 供应商应付款（人和公司）
#  - 供应商预付款（公司和公司）
#  - 供应商预付款（人和公司）
#  - 重要其他应付款（公司和公司）
#  - 重要其他应付款（人和公司）
#  债权:
#  - 关联交易—资金拆借（公司和公司）
#  - 关联交易—资金拆借（人和公司）<-
#  - 关联交易—资金拆借（公司和人）
#  担保:
#  - 担保（公司和公司）
##  竞争对手:
##  -
#  业务:
#  - 主营产品
#  - 非上市主营产品










